# -*- coding: utf-8 -*-
"""Testing 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XfpXTx8N5eyD8JGnLrjMwCaYK7K5sDdp
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# ==========================================
# 1. LOAD AND PREPARE THE SINGLE DATASET
# ==========================================
# Ensure 'future_gpa_dataset_final.csv' is uploaded to Colab!
df = pd.read_csv("future_gpa_dataset_final.csv")

# If your CSV uses letters for O/L results (A, B, C, S, W/F), we must convert them to numbers for the AI:
grade_mapping = {'A': 4, 'B': 3, 'C': 2, 'S': 1, 'W': 0, 'F': 0}

# Replace letters with numbers (Skip this if your CSV already uses numbers)
if df['OL_Maths'].dtype == object:
    df['OL_Maths'] = df['OL_Maths'].map(grade_mapping)
if df['OL_English'].dtype == object:
    df['OL_English'] = df['OL_English'].map(grade_mapping)

df = df.dropna() # Clean any missing data
y_target = df['Future_GPA']

# ==========================================
# 2. FEATURE SELECTION (The Magic Trick!)
# ==========================================
# Model A gets Previous GPA (Ignores O/L Results)
features_model_a = [
    'Previous_GPA', 'Attendance_Percentage',
    'Study_Hours_Per_Week', 'Sleep_Hours_Per_Day', 'Stress_Level'
]

# Model B gets O/L Results (Ignores Previous GPA)
features_model_b = [
    'OL_Maths', 'OL_English', 'Attendance_Percentage',
    'Study_Hours_Per_Week', 'Sleep_Hours_Per_Day', 'Stress_Level'
]

X_model_a = df[features_model_a]
X_model_b = df[features_model_b]

# Split Data (80% Train, 20% Test)
Xa_train, Xa_test, ya_train, ya_test = train_test_split(X_model_a, y_target, test_size=0.2, random_state=42)
Xb_train, Xb_test, yb_train, yb_test = train_test_split(X_model_b, y_target, test_size=0.2, random_state=42)

# ==========================================
# 3. TRAIN BOTH MODELS
# ==========================================
model_a = LinearRegression().fit(Xa_train, ya_train)
model_b = LinearRegression().fit(Xb_train, yb_train)

# Generate Predictions (Constrain to 0.0 - 4.0 max GPA)
pred_a = np.clip(model_a.predict(Xa_test), 0.0, 4.0)
pred_b = np.clip(model_b.predict(Xb_test), 0.0, 4.0)

# ==========================================
# 4. EVALUATE & COMPARE
# ==========================================
print("======================================================")
print(" 🎓 DUAL MODEL ML EVALUATION")
print("======================================================")

# Evaluate Model A
r2_a = r2_score(ya_test, pred_a)
mae_a = mean_absolute_error(ya_test, pred_a)

print("\n--- MODEL A: Returning Students ---")
print("Features used: Previous GPA + 4 Lifestyle Factors")
print(f"Accuracy (R²):       {r2_a*100:.1f}%")
print(f"Error Margin (MAE):  {mae_a:.4f} GPA Points")

# Evaluate Model B
r2_b = r2_score(yb_test, pred_b)
mae_b = mean_absolute_error(yb_test, pred_b)

print("\n--- MODEL B: New 1st Sem Students ---")
print("Features used: O/L Maths + O/L English + 4 Lifestyle Factors")
print(f"Accuracy (R²):       {r2_b*100:.1f}%")
print(f"Error Margin (MAE):  {mae_b:.4f} GPA Points")

# Check if Model B improved compared to our old 18.98% disaster!
if r2_b > 0.19:
    print("\n✅ SUCCESS: Adding O/L results massively boosted Model B's accuracy!")

# ==========================================
# INTERACTIVE PREDICTION TEST
# ==========================================
print("--- GPA PREDICTION TESTER ---")
print("Which type of student are you predicting for?")
print("1. Returning Student (Has a Previous GPA)")
print("2. New 1st Semester Student (Uses O/L Results)")

student_type = input("Enter 1 or 2: ")

try:
    if student_type == "1":
        print("\n--- ENTER DETAILS (MODEL A) ---")
        prev_gpa = float(input("1. Previous GPA (0.0 - 4.0): "))
        att = float(input("2. Average Attendance Percentage (0 - 100): "))
        study = float(input("3. Study Hours Per Week (e.g., 20): "))
        sleep = float(input("4. Sleep Hours Per Day (e.g., 7.5): "))
        stress = float(input("5. Stress Level (1.0 to 5.0): "))

        # Format the data exactly as Model A expects
        student_data = pd.DataFrame([[prev_gpa, att, study, sleep, stress]], columns=features_model_a)

        # Predict using Model A
        raw_pred = model_a.predict(student_data)[0]
        final_pred = round(np.clip(raw_pred, 0.0, 4.0), 2)

        print("\n=========================================")
        print(f"📊 MODEL A PREDICTED GPA: {final_pred}")
        print("=========================================")

    elif student_type == "2":
        print("\n--- ENTER DETAILS (MODEL B) ---")

        # O/L inputs as text, convert to uppercase just in case
        ol_maths_str = input("1. O/L Maths Result (A, B, C, S, W): ").strip().upper()
        ol_eng_str = input("2. O/L English Result (A, B, C, S, W): ").strip().upper()

        att = float(input("3. Target Attendance Percentage (0 - 100): "))
        study = float(input("4. Target Study Hours Per Week (e.g., 20): "))
        sleep = float(input("5. Sleep Hours Per Day (e.g., 7.5): "))
        stress = float(input("6. Stress Level (1.0 to 5.0): "))

        # Dictionary to convert letters to math values
        grade_mapping = {'A': 4, 'B': 3, 'C': 2, 'S': 1, 'W': 0, 'F': 0}

        # Convert user's letter grades to numbers
        ol_maths_val = grade_mapping.get(ol_maths_str, 0) # defaults to 0 if invalid
        ol_eng_val = grade_mapping.get(ol_eng_str, 0)

        # Format the data exactly as Model B expects
        student_data = pd.DataFrame([[ol_maths_val, ol_eng_val, att, study, sleep, stress]], columns=features_model_b)

        # Predict using Model B
        raw_pred = model_b.predict(student_data)[0]
        final_pred = round(np.clip(raw_pred, 0.0, 4.0), 2)

        print("\n=========================================")
        print(f"📊 MODEL B PREDICTED GPA: {final_pred}")
        print("=========================================")

    else:
        print("\n[Error] Invalid choice! Please run the cell again and enter 1 or 2.")

except ValueError:
    print("\n[Error] Invalid input detected! Please make sure you enter numbers for attendance, sleep, etc.")

# ==========================================
# INTERACTIVE PREDICTION TEST (STRICT VALIDATION)
# ==========================================
import pandas as pd
import numpy as np

print("--- GPA PREDICTION TESTER ---")
print("Which type of student are you predicting for?")
print("1. Returning Student (Has a Previous GPA)")
print("2. New 1st Semester Student (Uses O/L Results)")

while True:
    student_type = input("Enter 1 or 2: ").strip()
    if student_type in ['1', '2']:
        break
    print("[Error] Please enter exactly 1 or 2.")

# --- SHARED VALIDATION FUNCTIONS ---
def get_valid_attendance():
    while True:
        try:
            att = float(input("Average Attendance Percentage (0 - 100): "))
            if att < 0:
                print("[Error] Negative numbers are not allowed!")
            elif att > 100:
                print("[Error] Attendance cannot be above 100%.")
            else:
                if att < 80:
                    print("  ⚠️ [Warning] You need at least 80% attendance to be eligible for exams!")
                return att
        except ValueError:
            print("[Error] Please enter a valid number.")

def get_valid_study_hours():
    # Using Saegis/BIT By-Law calculations
    while True:
        try:
            credits = float(input("Total Credits taking this semester (e.g., 15): "))
            if credits <= 0:
                print("[Error] Credits must be a positive number greater than 0. No negatives allowed.")
            else:
                break
        except ValueError:
            print("[Error] Please enter a valid number.")

    # Calculation: (Credits * 50 notional hours) / 15 weeks
    min_hours = (credits * 50) / 15
    print(f"  📘 Based on BIT By-Laws, your minimum required study time is {min_hours:.1f} hours/week.")

    while True:
        try:
            study = float(input(f"Study Hours Per Week (Must be >= {min_hours:.1f}): "))
            if study < 0:
                print("[Error] Negative numbers are not allowed!")
            elif study >= min_hours and study <= 168:
                return study
            elif study < min_hours:
                print(f"[Error] According to BIT By-Laws, you must study at least {min_hours:.1f} hours.")
            else:
                print("[Error] There are only 168 hours in a week!")
        except ValueError:
            print("[Error] Please enter a valid number.")

def get_valid_sleep():
    while True:
        try:
            sleep = float(input("Sleep Hours Per Day (5, 6, 7, 8, or 9): "))
            if sleep < 0:
                print("[Error] Negative numbers are not allowed!")
            elif sleep in [5.0, 6.0, 7.0, 8.0, 9.0]:
                return sleep
            else:
                print("[Error] Invalid. Healthy sleep hours must be exactly 5, 6, 7, 8, or 9.")
        except ValueError:
            print("[Error] Please enter a valid number.")

def get_valid_stress():
    while True:
        try:
            stress = float(input("Stress Level (0.0 to 5.0): "))
            if stress < 0:
                print("[Error] Negative numbers are not allowed!")
            elif stress > 5.0:
                print("[Error] Stress level cannot be higher than 5.0.")
            else:
                return stress
        except ValueError:
            print("[Error] Please enter a valid number.")

# ==========================================
# MAIN EXECUTION
# ==========================================
if student_type == "1":
    print("\n--- ENTER DETAILS (MODEL A) ---")

    # Validate Previous GPA
    while True:
        try:
            prev_gpa = float(input("Previous GPA (0.00 - 4.00): "))
            if prev_gpa < 0:
                print("[Error] Negative numbers are not allowed!")
            elif prev_gpa > 4.0:
                print("[Error] Previous GPA cannot be higher than 4.00.")
            else:
                break
        except ValueError:
            print("[Error] Please enter a valid number.")

    att = get_valid_attendance()
    study = get_valid_study_hours()
    sleep = get_valid_sleep()
    stress = get_valid_stress()

    # Predict using Model A
    student_data = pd.DataFrame([[prev_gpa, att, study, sleep, stress]], columns=features_model_a)
    raw_pred = model_a.predict(student_data)[0]
    final_pred = round(np.clip(raw_pred, 0.0, 4.0), 2)

    print("\n=========================================")
    print(f"📊 MODEL A PREDICTED GPA: {final_pred}")
    print("=========================================")

elif student_type == "2":
    print("\n--- ENTER DETAILS (MODEL B) ---")
    grade_mapping = {'A': 4, 'B': 3, 'C': 2, 'S': 1, 'W': 0, 'F': 0}

    # Validate O/L Maths
    while True:
        ol_maths_str = input("O/L Maths Result (A, B, C, S, W): ").strip().upper()
        if ol_maths_str in grade_mapping:
            break
        print("[Error] Invalid grade. Must be A, B, C, S, or W.")

    # Validate O/L English
    while True:
        ol_eng_str = input("O/L English Result (A, B, C, S, W): ").strip().upper()
        if ol_eng_str in grade_mapping:
            break
        print("[Error] Invalid grade. Must be A, B, C, S, or W.")

    ol_maths_val = grade_mapping[ol_maths_str]
    ol_eng_val = grade_mapping[ol_eng_str]

    att = get_valid_attendance()
    study = get_valid_study_hours()
    sleep = get_valid_sleep()
    stress = get_valid_stress()

    # Predict using Model B
    student_data = pd.DataFrame([[ol_maths_val, ol_eng_val, att, study, sleep, stress]], columns=features_model_b)
    raw_pred = model_b.predict(student_data)[0]
    final_pred = round(np.clip(raw_pred, 0.0, 4.0), 2)

    print("\n=========================================")
    print(f"📊 MODEL B PREDICTED GPA: {final_pred}")
    print("=========================================")

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

# Set the visual style for professional panel presentation
sns.set_theme(style="whitegrid", palette="muted")

# 1. GENERATE CORRELATION HEATMAP (Evidence of overall impact)
# (Assuming df is already loaded from the previous code block)
plt.figure(figsize=(10, 8))

# Calculate the correlation mathematically
correlation_matrix = df.corr()

# Draw the heatmap
sns.heatmap(correlation_matrix[['Future_GPA']].sort_values(by='Future_GPA', ascending=False),
            annot=True, cmap="coolwarm", fmt=".2f", linewidths=1, vmin=-1, vmax=1)

plt.title("Correlation: Impact of All Features on Future GPA", fontsize=16, fontweight='bold', pad=20)
plt.ylabel("Features", fontsize=12)
plt.show()

# ==========================================
# 2. FEATURE IMPORTANCE: MODEL A (Returning Students)
# ==========================================
# Extract the AI's internal mathematical weights (coefficients)
coeff_a = pd.DataFrame(model_a.coef_, X_model_a.columns, columns=['Weight'])
coeff_a = coeff_a.sort_values(by='Weight', ascending=True)

plt.figure(figsize=(10, 5))
coeff_a['Weight'].plot(kind='barh', color='teal', edgecolor='black')

plt.title("Model A (Returning): Which Features Impact GPA the Most?", fontsize=14, fontweight='bold')
plt.xlabel("Impact Weight (Coefficient)", fontsize=12)
plt.ylabel("Selected Features", fontsize=12)
plt.axvline(x=0, color='red', linestyle='--', linewidth=1.5) # Draw a 0-line
plt.show()

# ==========================================
# 3. FEATURE IMPORTANCE: MODEL B (New Students)
# ==========================================
# Extract the AI's internal mathematical weights (coefficients)
coeff_b = pd.DataFrame(model_b.coef_, X_model_b.columns, columns=['Weight'])
coeff_b = coeff_b.sort_values(by='Weight', ascending=True)

plt.figure(figsize=(10, 5))
coeff_b['Weight'].plot(kind='barh', color='darkorange', edgecolor='black')

plt.title("Model B (New Students): Which Features Impact GPA the Most?", fontsize=14, fontweight='bold')
plt.xlabel("Impact Weight (Coefficient)", fontsize=12)
plt.ylabel("Selected Features", fontsize=12)
plt.axvline(x=0, color='red', linestyle='--', linewidth=1.5) # Draw a 0-line
plt.show()