# -*- coding: utf-8 -*-
"""three models testing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TZpKZL7W76nbVU0mcmMToKiLJzAsE3Os
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# ==========================================
# 1. LOAD THE DATASET
# ==========================================
df = pd.read_csv("future_gpa_dataset_final.csv").dropna()
y_target = df['Future_GPA']

# ==========================================
# 2. FEATURE SELECTION (TRI-MODEL SUITE)
# ==========================================
features_model_a = [
    'Previous_GPA', 'Attendance_Percentage',
    'Study_Hours_Per_Week', 'Sleep_Hours_Per_Day', 'Stress_Level'
]

features_model_b = [
    'Mid_Mark', 'Assignment_Mark', 'Attendance_Percentage',
    'Study_Hours_Per_Week', 'Sleep_Hours_Per_Day', 'Stress_Level'
]

# The Master Model: Combines History + Current Academic Performance + Lifestyle
features_model_c = [
    'Previous_GPA', 'Mid_Mark', 'Assignment_Mark', 'Attendance_Percentage',
    'Study_Hours_Per_Week', 'Sleep_Hours_Per_Day', 'Stress_Level'
]

X_model_a = df[features_model_a]
X_model_b = df[features_model_b]
X_model_c = df[features_model_c]

# Split Data (80% Train, 20% Test)
Xa_train, Xa_test, ya_train, ya_test = train_test_split(X_model_a, y_target, test_size=0.2, random_state=42)
Xb_train, Xb_test, yb_train, yb_test = train_test_split(X_model_b, y_target, test_size=0.2, random_state=42)
Xc_train, Xc_test, yc_train, yc_test = train_test_split(X_model_c, y_target, test_size=0.2, random_state=42)

# ==========================================
# 3. TRAIN ALL THREE MODELS
# ==========================================
model_a = LinearRegression().fit(Xa_train, ya_train)
model_b = LinearRegression().fit(Xb_train, yb_train)
model_c = LinearRegression().fit(Xc_train, yc_train)

# Predictions (Clipped to 0.0 - 4.0 max GPA)
pred_a = np.clip(model_a.predict(Xa_test), 0.0, 4.0)
pred_b = np.clip(model_b.predict(Xb_test), 0.0, 4.0)
pred_c = np.clip(model_c.predict(Xc_test), 0.0, 4.0)

# ==========================================
# 4. ADVANCED EVALUATION METRICS
# ==========================================
print("======================================================")
print(" 🎓 TRI-MODEL ML EVALUATION (LIFECYCLE SUITE)")
print("======================================================")

def evaluate_and_print(name, desc, y_test, preds, X_test):
    r2 = r2_score(y_test, preds)
    mae = mean_absolute_error(y_test, preds)
    mse = mean_squared_error(y_test, preds)
    rmse = np.sqrt(mse)

    n = len(y_test)
    p = X_test.shape[1]
    adj_r2 = 1 - (1 - r2) * (n - 1) / (n - p - 1)

    print(f"\n--- {name}: {desc} ---")
    print(f"1. R-Squared (R²):         {r2*100:.2f}%")
    print(f"2. Adjusted R-Squared:     {adj_r2*100:.2f}%")
    print(f"3. Mean Absolute Error:    {mae:.4f} GPA Points")
    print(f"4. Mean Squared Error:     {mse:.4f}")
    print(f"5. Root Mean Sq Error:     {rmse:.4f} GPA Points")

evaluate_and_print("MODEL A", "Pre-Semester Baseline (Returning Students)", ya_test, pred_a, Xa_test)
evaluate_and_print("MODEL B", "Mid-Semester Performance (New Students)", yb_test, pred_b, Xb_test)
evaluate_and_print("MODEL C", "Comprehensive Master Model (Returning Mid-Semester)", yc_test, pred_c, Xc_test)

# IMPORTANT: Ensure Cell 'hXJKb9tfp0yO' (which trains model_a, model_b, model_c) has been executed before running this cell.
import pandas as pd
import numpy as np

# --- DEFINE FEATURE COLUMNS LOCALLY TO PREVENT COLAB ERRORS ---
features_model_a = ['Previous_GPA', 'Attendance_Percentage', 'Study_Hours_Per_Week', 'Sleep_Hours_Per_Day', 'Stress_Level']
features_model_b = ['Mid_Mark', 'Assignment_Mark', 'Attendance_Percentage', 'Study_Hours_Per_Week', 'Sleep_Hours_Per_Day', 'Stress_Level']
features_model_c = ['Previous_GPA', 'Mid_Mark', 'Assignment_Mark', 'Attendance_Percentage', 'Study_Hours_Per_Day', 'Stress_Level']

print("======================================================")
print(" 🎓 ADVANCED GPA PREDICTION TESTER (MODULE-LEVEL)")
print("======================================================")
print("Which stage are you predicting for?")
print("1. Pre-Semester Baseline (Returning Student - Uses CGPA only)")
print("2. Mid-Semester Performance (New Student - Uses Mid & Assignment Marks only)")
print("3. Comprehensive Master (Returning Mid-Semester - Uses BOTH CGPA & Marks)")

while True:
    student_type = input("Enter 1, 2, or 3: ").strip()
    if student_type in ['1', '2', '3']:
        break
    print("[Error] Please enter exactly 1, 2, or 3.")

# --- VALIDATION FUNCTIONS ---
def get_valid_prev_gpa():
    while True:
        try:
            prev_gpa = float(input("Cumulative GPA (CGPA) (0.00 - 4.00): "))
            if 0.00 <= prev_gpa <= 4.00:
                return prev_gpa
            print("[Error] CGPA must be between 0.00 and 4.00.")
        except ValueError:
            print("[Error] Please enter a valid number.")

def get_valid_attendance():
    while True:
        try:
            att = float(input("\nAverage Attendance Percentage (0 - 100): "))
            if 0 <= att <= 100:
                if att < 80:
                    print("  ⚠️ [Warning] You need at least 80% attendance to be eligible for exams!")
                return att
            print("[Error] Attendance must be between 0 and 100%.")
        except ValueError:
            print("[Error] Please enter a valid number.")

def get_valid_study_hours(num_modules):
    # Assuming 1 module = 3 credits roughly (adjust if your university uses different standard)
    credits = num_modules * 3
    min_hours = (credits * 50) / 15
    print(f"\n  📘 Based on BIT By-Laws ({credits} credits), your minimum required study time is {min_hours:.1f} hours/week.")

    while True:
        try:
            study = float(input(f"Study Hours Per Week (Must be >= {min_hours:.1f}): "))
            if min_hours <= study <= 168:
                return study
            elif study < min_hours:
                print(f"[Error] According to BIT By-Laws, you must study at least {min_hours:.1f} hours.")
            else:
                print("[Error] There are only 168 hours in a week!")
        except ValueError:
            print("[Error] Please enter a valid number.")

def get_valid_sleep():
    while True:
        try:
            sleep = float(input("\nSleep Hours Per Day (0 - 24): "))
            if 0 <= sleep <= 24:
                if sleep < 7 or sleep > 9:
                    print("  ⚠️ [NSF Warning] The National Sleep Foundation recommends 7 to 9 hours for adults (18-64).")
                    print("  ⚠️ Deviating from this standard mathematically lowers your cognitive performance and predicted GPA in our ML Model.")
                else:
                    print("  ✅ Excellent! You are within the NSF recommended 7-9 hours of healthy sleep.")
                return sleep
            print("[Error] Sleep must be between 0 and 24 hours.")
        except ValueError:
            print("[Error] Please enter a valid number.")

def get_valid_stress():
    while True:
        try:
            stress = float(input("Stress Level (1.0 to 5.0): "))
            if 1.0 <= stress <= 5.0:
                return stress
            print("[Error] Stress level must be between 1.0 and 5.0.")
        except ValueError:
            print("[Error] Please enter a valid number.")

# ==========================================
# MAIN EXECUTION
# ==========================================

if student_type == "1":
    print("\n--- ENTER DETAILS (MODEL A: Pre-Semester) ---")
    prev_gpa = get_valid_prev_gpa()

    while True:
        try:
            num_modules = int(input("How many modules are you taking this semester? "))
            if num_modules > 0: break
            print("[Error] Must be greater than 0.")
        except: print("[Error] Enter a whole number.")

    att = get_valid_attendance()
    study = get_valid_study_hours(num_modules)
    sleep = get_valid_sleep()
    stress = get_valid_stress()

    # Predict using Model A
    student_data = pd.DataFrame([[prev_gpa, att, study, sleep, stress]], columns=features_model_a)
    raw_pred = model_a.predict(student_data)[0]
    final_pred = round(np.clip(raw_pred, 0.0, 4.0), 2)

    print("\n=========================================")
    print(f"📊 MODEL A PREDICTED SEMESTER GPA: {final_pred}")
    print("=========================================")

else:
    if student_type == "2":
        print("\n--- ENTER DETAILS (MODEL B: Mid-Semester New Student) ---")
    else:
        print("\n--- ENTER DETAILS (MODEL C: Mid-Semester Master) ---")
        prev_gpa = get_valid_prev_gpa()

    while True:
        try:
            num_modules = int(input("How many modules are you taking this semester? "))
            if num_modules > 0: break
            print("[Error] Must be greater than 0.")
        except: print("[Error] Enter a whole number.")

    valid_mid_marks = []
    valid_assg_marks = []
    failed_modules = 0

    # 🔄 MODULE-BY-MODULE LOOP
    for i in range(1, num_modules + 1):
        print(f"\n📝 --- Module {i} Marks ---")
        while True:
            try:
                mid = float(input(f"  Mid Exam Mark (0-20): "))
                if 0 <= mid <= 20: break
                print("  [Error] Must be between 0 and 20.")
            except: print("  [Error] Invalid number.")

        while True:
            try:
                assg = float(input(f"  Assignment Mark (0-20): "))
                if 0 <= assg <= 20: break
                print("  [Error] Must be between 0 and 20.")
            except: print("  [Error] Invalid number.")

        # 🚫 CA ELIGIBILITY CHECK
        if (mid + assg) < 8:
            print(f"  ❌ [INELIGIBLE] Total CA is {mid+assg}. You failed the continuous assessment for Module {i}.")
            failed_modules += 1
        else:
            print(f"  ✅ [ELIGIBLE] Total CA is {mid+assg}.")
            valid_mid_marks.append(mid)
            valid_assg_marks.append(assg)

    # If the student failed EVERYTHING
    if failed_modules == num_modules:
        print("\n=========================================")
        print("🚨 YOU FAILED ALL CONTINUOUS ASSESSMENTS.")
        print(f"📊 PREDICTED SEMESTER GPA: 0.00 (Grade: F)")
        print("=========================================")
    else:
        # Calculate Averages for the ML Model
        avg_mid = sum(valid_mid_marks) / len(valid_mid_marks)
        avg_assg = sum(valid_assg_marks) / len(valid_assg_marks)

        print(f"\n📊 ML Aggregation: Average Mid Mark across passed modules: {avg_mid:.1f}")
        print(f"📊 ML Aggregation: Average Assg Mark across passed modules: {avg_assg:.1f}")

        att = get_valid_attendance()
        study = get_valid_study_hours(num_modules)
        sleep = get_valid_sleep()
        stress = get_valid_stress()

        # Predict using ML
        if student_type == "2":
            student_data = pd.DataFrame([[avg_mid, avg_assg, att, study, sleep, stress]], columns=features_model_b)
            surviving_gpa = np.clip(model_b.predict(student_data)[0], 0.0, 4.0)
        else:
            student_data = pd.DataFrame([[prev_gpa, avg_mid, avg_assg, att, study, sleep, stress]], columns=features_model_c)
            surviving_gpa = np.clip(model_c.predict(student_data)[0], 0.0, 4.0)

        # Calculate Final Semester GPA (combining 0.0 for failed modules and ML prediction for passed modules)
        final_semester_gpa = ((surviving_gpa * len(valid_mid_marks)) + (0.00 * failed_modules)) / num_modules

        print("\n=========================================")
        print(f"✅ Predicted GPA for your {len(valid_mid_marks)} passed modules: {surviving_gpa:.2f}")
        if failed_modules > 0:
            print(f"❌ Penalty applied for {failed_modules} automatically failed modules (0.0 GPA).")
        print(f"🎓 FINAL PREDICTED SEMESTER GPA: {final_semester_gpa:.2f}")
        print("=========================================")

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

# Set visual style for professional, clean graphs
sns.set_theme(style="whitegrid", palette="muted")

print("======================================================")
print(" 📊 VISUALIZING MODEL INSIGHTS & FEATURE IMPORTANCE")
print("======================================================")

# ==========================================
# 1. CORRELATION HEATMAP
# ==========================================
plt.figure(figsize=(10, 8))
correlation_matrix = df.corr()

# Focus the heatmap specifically on what correlates with Future_GPA
sns.heatmap(
    correlation_matrix[['Future_GPA']].sort_values(by='Future_GPA', ascending=False),
    annot=True,
    cmap="coolwarm",
    fmt=".2f",
    linewidths=1,
    vmin=-1,
    vmax=1
)

plt.title("Correlation: Impact of All Features on Future GPA", fontsize=16, fontweight='bold', pad=20)
plt.ylabel("Features", fontsize=12)
plt.tight_layout()
plt.show()

# ==========================================
# ADVANCED STATISTICAL FIX: STANDARDIZED COEFFICIENTS
# Why? Raw regression coefficients are misleading when features use different units
# (e.g., GPA is 0-4, but Attendance is 0-100).
# Multiplying by the standard deviation (coef * std) calculates the true impact
# of a 1-standard-deviation change, putting all features on a level playing field!
# ==========================================

# ==========================================
# 2. FEATURE IMPORTANCE: MODEL A (Returning Students)
# ==========================================
std_weights_a = model_a.coef_ * X_model_a.std(axis=0)
coeff_a = pd.DataFrame({'Standardized_Weight': std_weights_a}, index=X_model_a.columns)
coeff_a = coeff_a.sort_values(by='Standardized_Weight', ascending=True)

plt.figure(figsize=(10, 5))
coeff_a['Standardized_Weight'].plot(kind='barh', color='teal', edgecolor='black')
plt.title("Model A (Pre-Semester Baseline): True Feature Impact", fontsize=14, fontweight='bold')
plt.xlabel("Impact of 1 Standard Deviation Increase on Future GPA", fontsize=12)
plt.ylabel("Selected Features", fontsize=12)
plt.axvline(x=0, color='red', linestyle='--', linewidth=1.5)
plt.tight_layout()
plt.show()

# ==========================================
# 3. FEATURE IMPORTANCE: MODEL B (New Students Mid-Semester)
# ==========================================
std_weights_b = model_b.coef_ * X_model_b.std(axis=0)
coeff_b = pd.DataFrame({'Standardized_Weight': std_weights_b}, index=X_model_b.columns)
coeff_b = coeff_b.sort_values(by='Standardized_Weight', ascending=True)

plt.figure(figsize=(10, 5))
coeff_b['Standardized_Weight'].plot(kind='barh', color='darkorange', edgecolor='black')
plt.title("Model B (New Students Mid-Semester): True Feature Impact", fontsize=14, fontweight='bold')
plt.xlabel("Impact of 1 Standard Deviation Increase on Future GPA", fontsize=12)
plt.ylabel("Selected Features", fontsize=12)
plt.axvline(x=0, color='red', linestyle='--', linewidth=1.5)
plt.tight_layout()
plt.show()

# ==========================================
# 4. FEATURE IMPORTANCE: MODEL C (Master Model - Returning Mid-Semester)
# ==========================================
std_weights_c = model_c.coef_ * X_model_c.std(axis=0)
coeff_c = pd.DataFrame({'Standardized_Weight': std_weights_c}, index=X_model_c.columns)
coeff_c = coeff_c.sort_values(by='Standardized_Weight', ascending=True)

plt.figure(figsize=(10, 6))
coeff_c['Standardized_Weight'].plot(kind='barh', color='purple', edgecolor='black')
plt.title("Model C (Master Model): True Feature Impact", fontsize=14, fontweight='bold')
plt.xlabel("Impact of 1 Standard Deviation Increase on Future GPA", fontsize=12)
plt.ylabel("Selected Features", fontsize=12)
plt.axvline(x=0, color='red', linestyle='--', linewidth=1.5)
plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
import numpy as np

# Set professional visual style
sns.set_theme(style="whitegrid", palette="muted")

print("======================================================")
print(" 📊 VISUALIZING MODEL INSIGHTS & DIAGNOSTICS (CELL 3)")
print("======================================================")

# ==========================================
# 1. CORRELATION HEATMAP
# ==========================================
plt.figure(figsize=(10, 8))
correlation_matrix = df.corr()

sns.heatmap(
    correlation_matrix[['Future_GPA']].sort_values(by='Future_GPA', ascending=False),
    annot=True, cmap="coolwarm", fmt=".2f", linewidths=1, vmin=-1, vmax=1
)

plt.title("Correlation: Impact of All Features on Future GPA", fontsize=15, fontweight='bold', pad=15)
plt.ylabel("Features", fontsize=12)
plt.tight_layout()
plt.show()

# ==========================================
# 2. STANDARDIZED FEATURE IMPORTANCE (MODELS A, B, C)
# ==========================================

# --- Model A (Pre-Semester Baseline) ---
std_weights_a = model_a.coef_ * X_model_a.std(axis=0)
coeff_a = pd.DataFrame({'Standardized_Weight': std_weights_a}, index=X_model_a.columns).sort_values(by='Standardized_Weight', ascending=True)

plt.figure(figsize=(10, 4.5))
coeff_a['Standardized_Weight'].plot(kind='barh', color='teal', edgecolor='black')
plt.title("Model A (Pre-Semester): True Feature Impact (Standardized)", fontsize=13, fontweight='bold')
plt.xlabel("Impact of 1 Standard Deviation Increase on GPA", fontsize=11)
plt.ylabel("Selected Features", fontsize=11)
plt.axvline(x=0, color='red', linestyle='--', linewidth=1.5)
plt.tight_layout()
plt.show()

# --- Model B (New Students Mid-Semester) ---
std_weights_b = model_b.coef_ * X_model_b.std(axis=0)
coeff_b = pd.DataFrame({'Standardized_Weight': std_weights_b}, index=X_model_b.columns).sort_values(by='Standardized_Weight', ascending=True)

plt.figure(figsize=(10, 4.5))
coeff_b['Standardized_Weight'].plot(kind='barh', color='darkorange', edgecolor='black')
plt.title("Model B (New Students): True Feature Impact (Standardized)", fontsize=13, fontweight='bold')
plt.xlabel("Impact of 1 Standard Deviation Increase on GPA", fontsize=11)
plt.ylabel("Selected Features", fontsize=11)
plt.axvline(x=0, color='red', linestyle='--', linewidth=1.5)
plt.tight_layout()
plt.show()

# --- Model C (Master Model) ---
std_weights_c = model_c.coef_ * X_model_c.std(axis=0)
coeff_c = pd.DataFrame({'Standardized_Weight': std_weights_c}, index=X_model_c.columns).sort_values(by='Standardized_Weight', ascending=True)

plt.figure(figsize=(10, 5))
coeff_c['Standardized_Weight'].plot(kind='barh', color='purple', edgecolor='black')
plt.title("Model C (Master Model): True Feature Impact (Standardized)", fontsize=13, fontweight='bold')
plt.xlabel("Impact of 1 Standard Deviation Increase on GPA", fontsize=11)
plt.ylabel("Selected Features", fontsize=11)
plt.axvline(x=0, color='red', linestyle='--', linewidth=1.5)
plt.tight_layout()
plt.show()

# ==========================================
# 3. ADVANCED A+ SECTION: REGRESSION DIAGNOSTICS (MODEL C)
# ==========================================
# Calculate residuals for test set predictions
residuals_c = yc_test - pred_c

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

# Chart 1: Actual vs. Predicted GPA (Fit Quality)
axes[0].scatter(yc_test, pred_c, alpha=0.6, color='purple', edgecolors='k', s=40)
axes[0].plot([0.7, 4.0], [0.7, 4.0], 'r--', lw=2, label='Perfect Prediction Line (y=x)')
axes[0].set_title("Actual vs. Predicted GPA (Test Set)", fontsize=13, fontweight='bold')
axes[0].set_xlabel("Actual Future GPA", fontsize=11)
axes[0].set_ylabel("Predicted Future GPA", fontsize=11)
axes[0].set_xlim(0.7, 4.05)
axes[0].set_ylim(0.7, 4.05)
axes[0].legend(loc='upper left')

# Chart 2: Residuals vs. Predicted (Check for Homoscedasticity / Bias)
axes[1].scatter(pred_c, residuals_c, alpha=0.6, color='dodgerblue', edgecolors='k', s=40)
axes[1].axhline(y=0, color='red', linestyle='--', lw=2)
axes[1].set_title("Residuals vs. Predicted (Error Check)", fontsize=13, fontweight='bold')
axes[1].set_xlabel("Predicted Future GPA", fontsize=11)
axes[1].set_ylabel("Prediction Error (Residuals)", fontsize=11)

# Chart 3: Residual Distribution (Check for Normal Error Curve)
sns.histplot(residuals_c, kde=True, ax=axes[2], color='seagreen', bins=20, edgecolor='black')
axes[2].axvline(x=0, color='red', linestyle='--', lw=2)
axes[2].set_title("Residual Error Distribution (Normality)", fontsize=13, fontweight='bold')
axes[2].set_xlabel("GPA Error Margin", fontsize=11)
axes[2].set_ylabel("Student Count", fontsize=11)

plt.suptitle("Master Model (Model C) Statistical Diagnostics & Fit Verification", fontsize=15, fontweight='bold', y=1.03)
plt.tight_layout()
plt.show()